#!/bin/bash
# This script will help diagnose the production issue

echo "=== Diagnostic Script for PythonAnywhere Production Issue ==="
echo ""
echo "Run these commands on your PythonAnywhere bash console:"
echo ""
echo "# 1. Check if the app can start at all"
echo "cd ~/total_bankroll"
echo "workon bankroll_venv"
echo "export FLASK_APP='src/total_bankroll'"
echo "python << 'PYEOF'"
echo "from src.total_bankroll import create_app"
echo "try:"
echo "    app = create_app('production')"
echo "    print('✅ App created successfully')"
echo "    print(f'Cache type: {app.config.get(\"CACHE_TYPE\")}')"
echo "    print(f'Environment: {app.config.get(\"FLASK_ENV\")}')"
echo "except Exception as e:"
echo "    print(f'❌ Error creating app: {e}')"
echo "    import traceback"
echo "    traceback.print_exc()"
echo "PYEOF"
echo ""
echo "# 2. Check the actual error log with more lines"
echo "tail -100 /var/log/pythonpydev.pythonanywhere.com.error.log"
echo ""
echo "# 3. Check server log"
echo "tail -100 /var/log/pythonpydev.pythonanywhere.com.server.log"
echo ""
echo "# 4. Verify .env file has no hidden characters"
echo "cat -A ~/total_bankroll/.env | grep -E '(CACHE_TYPE|CHROME_BINARY)'"
echo ""
echo "# 5. Test if Flask can serve a simple request"
echo "cd ~/total_bankroll"
echo "export FLASK_APP='src/total_bankroll'"
echo "python -c 'from src.total_bankroll import create_app; app = create_app(\"production\"); print(app.url_map)'"

