"""empty message

Revision ID: 28d060ce6615
Revises: a092fcdc2ff5
Create Date: 2025-10-26 08:44:34.735146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d060ce6615'
down_revision = 'a092fcdc2ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        # Step 1: Add the column as nullable
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # Step 2: Update existing rows with the current time
    op.execute('UPDATE articles SET last_updated = NOW() WHERE last_updated IS NULL')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        # Step 3: Alter the column to be non-nullable
        batch_op.alter_column('last_updated', existing_type=sa.DateTime(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
