"""Add default currency to user model

Revision ID: 2b461a823f18
Revises: f4f52aa82318
Create Date: 2025-09-02 19:54:18.543590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b461a823f18'
down_revision = 'f4f52aa82318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_currency_code', sa.String(length=3), nullable=False))
        batch_op.create_foreign_key(None, 'currency', ['default_currency_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_currency_code')

    # ### end Alembic commands ###
