"""empty message

Revision ID: 4b257b0997ff
Revises: 16f6f1c7e19f
Create Date: 2025-10-25 17:42:25.352290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b257b0997ff'
down_revision = '16f6f1c7e19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('content_md',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('content_html',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('content_html',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('content_md',
               existing_type=mysql.TEXT(),
               nullable=False)

    op.drop_table('goals')
    # ### end Alembic commands ###
