"""Add display_order to sites table

Revision ID: 5e19a2149a34
Revises: f4f52aa82318
Create Date: 2025-09-03 09:38:10.611294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e19a2149a34'
down_revision = 'f4f52aa82318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - manually reordered for correctness ###

    # Step 1: Add the unique constraint to the currency table first.
    # This is required before any other table can create a foreign key to it.
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_currency_code', ['code'])

    # Step 2: Now, alter all other tables that depend on it.
    with op.batch_alter_table('asset_history', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_asset_history_currency', 'currency', ['currency'], ['code'])

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_deposits_currency', 'currency', ['currency'], ['code'])

    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_drawings_currency', 'currency', ['currency'], ['code'])

    with op.batch_alter_table('site_history', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_site_history_currency', 'currency', ['currency'], ['code'])

    # Step 3: Add the new column to the sites table
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))

    # Step 4: Add the foreign key to the users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_default_currency_code', 'currency', ['default_currency_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - manually reordered for correctness ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_default_currency_code', type_='foreignkey')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    with op.batch_alter_table('site_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_site_history_currency', type_='foreignkey')
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drawings_currency', type_='foreignkey')
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deposits_currency', type_='foreignkey')
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_constraint('uq_currency_code', type_='unique')

    with op.batch_alter_table('asset_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_history_currency', type_='foreignkey')
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
