"""Add 2FA fields to User model

Revision ID: 61749658ada6
Revises: d064108bb1f6
Create Date: 2025-09-17 11:53:11.252903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61749658ada6'
down_revision = 'd064108bb1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('otp_enabled', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'currency', ['default_currency_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('otp_enabled')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
