"""Remove withdrawn_at and deposited_at columns

Revision ID: dc3f1b4ff245
Revises: be7d467170ba
Create Date: 2025-08-29 18:30:00.885363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc3f1b4ff245'
down_revision = 'be7d467170ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_stakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('small_blind', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('big_blind', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_buy_in', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_buy_in', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_column('withdrawn_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawn_at', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    op.drop_table('cash_stakes')
    # ### end Alembic commands ###
