"""empty message

Revision ID: f3e59f037f69
Revises: ce9c7ec16148
Create Date: 2025-10-26 07:13:24.812780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e59f037f69'
down_revision = 'ce9c7ec16148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tool_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_key', sa.String(length=50), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tool_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tool_usage')
    # ### end Alembic commands ###
