"""Remove deposited_at column from Deposits

Revision ID: f4f52aa82318
Revises: dc3f1b4ff245
Create Date: 2025-08-30 08:07:28.253452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4f52aa82318'
down_revision = 'dc3f1b4ff245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_column('deposited_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposited_at', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
