"""
Seed articles from markdown files in resources/articles/markdown.
"""
import os
from datetime import datetime
from src.total_bankroll import create_app
from src.total_bankroll.models import db, Article

ARTICLES_DIR = os.path.join(os.path.dirname(__file__), '../resources/articles/markdown')

def get_title_from_markdown(md_path):
    with open(md_path, encoding='utf-8') as f:
        for line in f:
            if line.strip().startswith('# '):
                return line.strip().lstrip('# ').strip()
        # fallback: filename without extension
        return os.path.splitext(os.path.basename(md_path))[0].replace('-', ' ')

def main():
    app = create_app()
    with app.app_context():
        for fname in os.listdir(ARTICLES_DIR):
            if not fname.endswith('.md'):
                continue
            path = os.path.join(ARTICLES_DIR, fname)
            title = get_title_from_markdown(path)
            with open(path, encoding='utf-8') as f:
                content_md = f.read()
            # Check if article already exists by title
            article = Article.query.filter_by(title=title).first()
            if article:
                print(f"Skipping existing: {title}")
                continue
            article = Article(
                title=title,
                content_md=content_md,
                content_html='',  # Will be auto-generated by event
                date_published=datetime.utcnow(),
                last_updated=datetime.utcnow(),
                author_id=None
            )
            db.session.add(article)
            print(f"Added: {title}")
        db.session.commit()
        print("All markdown articles seeded.")

if __name__ == '__main__':
    main()
