CREATE TABLE IF NOT EXISTS sites (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    last_updated DATETIME NOT NULL,
    currency VARCHAR(255) NOT NULL DEFAULT 'Dollar'
);

CREATE TABLE IF NOT EXISTS assets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    last_updated DATETIME NOT NULL,
    currency VARCHAR(255) NOT NULL DEFAULT 'Dollar'
);

CREATE TABLE IF NOT EXISTS drawings (
    id INT PRIMARY KEY AUTO_INCREMENT,
    date DATETIME NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    withdrawn_at DECIMAL(10, 2) NOT NULL,
    last_updated DATETIME NOT NULL,
    currency VARCHAR(255) NOT NULL DEFAULT 'Dollar'
);

CREATE TABLE IF NOT EXISTS deposits (
    id INT PRIMARY KEY AUTO_INCREMENT,
    date DATETIME NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    deposited_at DECIMAL(10, 2) NOT NULL,
    last_updated DATETIME NOT NULL,
    currency VARCHAR(255) NOT NULL DEFAULT 'Dollar'
);

CREATE TABLE IF NOT EXISTS currency (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    rate DECIMAL(10, 6) NOT NULL,
    code VARCHAR(3) NOT NULL,
    symbol VARCHAR(5) NOT NULL
);
